### ISSUE TITLE
Investigate 502 Bad Gateway error

### ISSUE THREAD

**Issue by Siegrift** [api3dao/signed-api#143]
The following warning was present in Airseeker logs, which seems to be an issue with signed API.

```json
{
    "code": "ERR_BAD_RESPONSE",
    "dataFetcherCoordinatorId": "1700933727802",
    "level": "warn",
    "message": "Request failed with status code 502",
    "ms": "+36ms",
    "name": "AxiosError",
    "response": {
        "data": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n",
        "headers": {
            "connection": "close",
            "content-length": "122",
            "content-type": "text/html",
            "date": "Sat, 25 Nov 2023 17:35:27 GMT",
            "server": "awselb/2.0"
        },
        "status": 502
    },
    "stack": "AxiosError: Request failed with status code 502\n    at settle (/app/node_modules/.pnpm/axios@1.6.0/node_modules/axios/dist/node/axios.cjs:1913:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.6.0/node_modules/axios/dist/node/axios.cjs:3008:11)\n    at IncomingMessage.emit (node:events:529:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1368:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "timestamp": "2023-11-25T17:35:27.838Z"
}
```

**Comment by Siegrift** [comment]
This one is very hard to debug, because this error was thrown by the load balancer and haven't reached the Signed API container at all (meaning there are no logs). Also, this issue happened only once and there is nothing suspicious shortly before or after this incident.

I'm closing this without resolution and we can re-investigate if this becomes a recurring problem.
